Failed to convert dandiset 000072: 2 validation errors for Dandiset
contributor
  List should have at least 1 item after validation, not 0 [type=too_short, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.11/v/too_short
license
  List should have at least 1 item after validation, not 0 [type=too_short, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.11/v/too_short

Traceback:
Traceback (most recent call last):
  File "/home/runner/work/nwb2bids-dandisets-dashboard/nwb2bids-dandisets-dashboard/scripts/run_nwb2bids_on_dandisets.py", line 29, in <module>
    dataset_converter = nwb2bids.DatasetConverter.from_remote_dandiset(dandiset_id=dandiset_id)
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 39, in wrapper_function
    return wrapper(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/pydantic/_internal/_validate_call.py", line 136, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/nwb2bids/_converters/_dataset_converter.py", line 49, in from_remote_dandiset
    dandiset_metadata = dandiset.get_metadata()
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/dandi/dandiapi.py", line 1068, in get_metadata
    return models.Dandiset.model_validate(self.get_raw_metadata())
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/pydantic/main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context, by_alias=by_alias, by_name=by_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Dandiset
contributor
  List should have at least 1 item after validation, not 0 [type=too_short, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.11/v/too_short
license
  List should have at least 1 item after validation, not 0 [type=too_short, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.11/v/too_short
